version: '3.3'
services:
  db:
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: package_db
    ports:
      - 3307:3306
    volumes:
      - mysqldb:/var/lib/mysql
# Names our volume
volumes:
  mysqldb:
