version: '3.3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - DB_NAME=package_db
    ports:
      - 3307:3306
    command: mysqld --user=root
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
# Names our volume
volumes:
  db:
