version: '3.3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: package_db
    ports:
      - 3307:3306
    volumes:
      - mysqldb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 3
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Update the database host to the service name "db"
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: package_db
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3050:80"
    # depends_on:
    #   - backend
volumes:
  mysqldb:
