name: Frontend CI/CD

on:
  push:
    branches: [main]
    paths-ignore:
      - backend/**

jobs:
  # ==============
  # CI task
  # ==============
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Setup SHA
        run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      # - name: Integration test inside Docker-compose
      #   run: make test-integration
      
      # - name: E2E test inside Docker-compose
      #   run: make test-e2e

      - name: Build Frontend the Docker image
        run: |
          ls
          docker build . -f ./frontend/Dockerfile --tag ghcr.io/frngrit/package-deliver/frontend:${{ env.GITHUB_SHA }} --progress=plain --no-cache
      
      - name: Login ghcr.io
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.WORKFLOW_TOKEN }}
          logout: true
      
      - name: Push Frontend Image to GitHub Container Registry
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./frontend
          tags: |
            ghcr.io/frngrit/package-deliver/frontend:${{ env.GITHUB_SHA }}
          push: true
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  # ==============
  # CD DEV task
  # ==============
  gitops-versioning:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: frngrit/delivery_argocd
          persist-credentials: false
          fetch-depth: 0
      - name: change image tag
        run: |
          git --version
          git config user.name "frngrit"
          git config user.email "frank.12876@hotmail.com"
          sed -i -E "s/ghcr.io\/frngrit\/package-deliver\/frontend.*$/ghcr.io\/frngrit\/package-deliver\/frontend:${GITHUB_SHA}/" kube-gitops/deployment.yml
          git add kube-gitops/deployment.yml
          git commit -m "🤖 change docker image version to ${GITHUB_SHA}"
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          repository: frngrit/delivery_argocd
          branch: main