name: Dev environment CI and CD

on:
  push:
    branches: [main, hotfix]

jobs:
  # ==============
  # CI task
  # ==============
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Setup SHA
        run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      # - name: Unit test
      #   run: make test-unit

      # - name: Integration test inside Docker-compose
      #   run: make test-integration
      
      # - name: E2E test inside Docker-compose
      #   run: make test-e2e

      - name: Build Backend the Docker image
        run: docker build -f ./backend/Dockerfile --tag ghcr.io/frngrit/package-deliver/backend:${{ env.GITHUB_SHA }}

      - name: Login ghcr.io
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.WORKFLOW_TOKEN }}
          logout: true
      
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          tags: |
            ghcr.io/frngrit/package-deliver/backend:${{ env.GITHUB_SHA }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
